import{S as w,a as S,i as a}from"./assets/vendor-DXKtl-Fy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".load-more"),v=new w(".gallery a",{captionsData:"alt",captionDelay:250});function f(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:n,comments:b,downloads:L})=>`
      <a href="${s}" class="gallery-item">
        <img src="${i}" alt="${e}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${L}</p>
        </div>
      </a>`).join("");h.insertAdjacentHTML("beforeend",t),v.refresh()}function E(){h.innerHTML=""}function p(){g.classList.remove("is-hidden")}function c(){g.classList.add("is-hidden")}function P(){m.classList.remove("is-hidden")}function u(){m.classList.add("is-hidden")}const q="52807381-7a65b057c23058f47f8cb5df4",R="https://pixabay.com/api/",B=15;async function y(o,t){const i={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B};try{return(await S.get(R,{params:i})).data}catch(s){throw console.error("Error fetching images:",s),s}}let l=1,d="";const M=document.querySelector("#search-form"),$=document.querySelector("#load-more");M.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.query.value.trim(),!d){a.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}l=1,E(),u(),p();try{const t=await y(d,l);if(t.hits.length===0){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c();return}f(t.hits),c(),t.totalHits>15?P():u()}catch{c(),a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}});$.addEventListener("click",async()=>{l+=1,p();try{const o=await y(d,l);f(o.hits),c();const t=Math.ceil(o.totalHits/15);l>=t&&(u(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:i}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}catch{c(),a.error({title:"Error",message:"Something went wrong while loading more images!",position:"topRight"})}});
//# sourceMappingURL=index.js.map
