import{S as h,a as g}from"./assets/vendor-C4LBg0wn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const l=document.querySelector(".gallery");document.querySelector(".loader");const d=document.querySelector(".load-more"),b=new h(".gallery a",{captionsData:"alt",captionDelay:250});function u(r){const o=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:a,comments:m,downloads:y})=>`
      <a href="${s}" class="gallery-item">
        <img src="${n}" alt="${e}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${m}</p>
          <p><b>Downloads:</b> ${y}</p>
        </div>
      </a>`).join("");l.insertAdjacentHTML("beforeend",o),b.refresh()}function L(){l.innerHTML=""}function v(){d.classList.remove("is-hidden")}function f(){d.classList.add("is-hidden")}const w="52807381-7a65b057c23058f47f8cb5df4",S="https://pixabay.com/api/",q=15;async function p(r,o){const n={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q};try{return(await g.get(S,{params:n})).data}catch(s){throw console.error("Error fetching images:",s),s}}let c=1,i="";const E=document.querySelector("#search-form"),P=document.querySelector("#load-more");E.addEventListener("submit",async r=>{r.preventDefault(),i=r.target.elements.query.value.trim(),c=1,L(),f();const o=await p(i,c);u(o.hits),o.totalHits>15&&v()});P.addEventListener("click",async()=>{c+=1;const r=await p(i,c);u(r.hits),c*15>=r.totalHits&&(f(),alert("We're sorry, but you've reached the end of search results."))});
//# sourceMappingURL=index.js.map
